name: CI

on:
  release:
    types: [created]


jobs:
  build:    
    name: Build0
    runs-on: self-hosted
    strategy:
      fail-fast: true
      matrix:
        projectPath: 
          - .
        targetPlatform:
          - StandaloneWindows
    steps:
      - uses: actions/checkout@v2
      - name: Run jobRunnerPowershell script
        run: .\runner_job.ps1
        shell: powershell
      - uses: rennat/upload-s3-action@master
        with:
          AWS_S3_BUCKET: 'vrh-test'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'Build'
          DEST_DIR: '/HelpClubWorldBundles/${{ github.repository }}/${{ github.ref }}/'
