name: CI

on:
  release:
    types: [created]


jobs:
  job1:    
    name: Build iOS Bundles
    runs-on: [self-hosted, macOS]
    strategy:
      fail-fast: true
      matrix:
        projectPath: 
          - .
        targetPlatform:
          - StandaloneWindows
    env:
      ACTION_LOG_FILE: "${{ github.run_id }}_${{ github.run_number }}.log"
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Run jobRunnerPowershell script
        run: .\runner_job.ps1
        shell: pwsh
      - uses: rennat/upload-s3-action@master
        with:
          AWS_S3_BUCKET: 'vrh-test'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'Build'
          DEST_DIR: '/HelpClubWorldBundles/${{ github.repository }}/${{ github.ref }}/'

  job2: 
    name: Build Other Bundles 
    runs-on: [self-hosted, windows, bundles]
    strategy:
      fail-fast: true
      matrix:
        projectPath: 
          - .
        targetPlatform:
          - StandaloneWindows
    env:
      ACTION_LOG_FILE: "${{ github.run_id }}_${{ github.run_number }}.log"
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Run jobRunnerPowershell script
        run: .\runner_job.ps1
        shell: powershell
      - uses: rennat/upload-s3-action@master
        with:
          AWS_S3_BUCKET: 'vrh-test'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'
          SOURCE_DIR: 'Build'
          DEST_DIR: '/HelpClubWorldBundles/${{ github.repository }}/${{ github.ref }}/'
